enableTelemetry: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs

packageExtensions:
  '@tiptap/core@*':
    dependencies:
      prosemirror-commands: '*'
      prosemirror-keymap: '*'
      prosemirror-model: '*'
      prosemirror-schema-list: '*'
      prosemirror-state: '*'
      prosemirror-transform: '*'
      prosemirror-view: '*'
  '@tiptap/react@*':
    dependencies:
      prosemirror-commands: '*'
      prosemirror-keymap: '*'
      prosemirror-model: '*'
      prosemirror-schema-list: '*'
      prosemirror-transform: '*'
      prosemirror-state: '*'
  '@tiptap/extension-bubble-menu@*':
    dependencies:
      prosemirror-commands: '*'
      prosemirror-keymap: '*'
      prosemirror-model: '*'
      prosemirror-schema-list: '*'
      prosemirror-transform: '*'
  '@tiptap/starter-kit@*':
    dependencies:
      prosemirror-commands: '*'
      prosemirror-gapcursor: '*'
      prosemirror-history: '*'
      prosemirror-keymap: '*'
      prosemirror-model: '*'
      prosemirror-schema-list: '*'
      prosemirror-state: '*'
      prosemirror-transform: '*'
      prosemirror-view: '*'
      prosemirror-dropcursor: '1.5.0'
